# version: '3.7'

# services:
#     todo_service:
#         build:
#             context: ./todo_service
#         container_name: todo_fastapi_container
#         ports:
#             - "8000:8000"
#         environment:
#             - DB_USER=root
#             - DB_PASSWORD=nsx@123
#             - DB_HOST=db
#             - DB_PORT=3307
#             - DB_NAME=test_todo_db
#         depends_on:
#             - db
#     db:
#         image: mysql:8.0
#         container_name: todo_mysql_container
#         environment:
#             - MYSQL_DATABASE=test_todo_db
#             - MYSQL_USER=root
#             - MYSQL_PASSWORD=nsx@123
#         ports:
#             - "3307:3306"  # Map external port 3307 to internal port 3306
#         volumes:
#             - mysql_data:/var/lib/mysql

# volumes:
#     mysql_data:

version: "3.7"

services:

  todo_service:
    build:
      context: ./todo_service
    container_name: todo_fastapi_container
    ports:
      - "8000:8000"
    environment:
      - DB_USER=temp_user
      - DB_PASSWORD=nsx%40123
      - DB_HOST=db
      - DB_PORT=3307
      - DB_NAME=test_todo_db
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    container_name: todo_mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=test_todo_db
      - MYSQL_USER=temp_user
      - MYSQL_PASSWORD=nsx@123
    ports:
      - "3307:3306" # Map external port 3307 to internal port 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: